clients/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views
from . import htmx


router = routers.DefaultRouter()
router.register("BureauScores", api.BureauScoresViewSet)
router.register("Client", api.ClientViewSet)
router.register("PDFInformation", api.PDFInformationViewSet)
router.register("RevolvingAccountsDetails", api.RevolvingAccountsDetailsViewSet)

urlpatterns = (
    path("api/v1/", include(router.urls)),
    path("clients/BureauScores/", views.BureauScoresListView.as_view(), name="clients_BureauScores_list"),
    path("clients/BureauScores/create/", views.BureauScoresCreateView.as_view(), name="clients_BureauScores_create"),
    path("clients/BureauScores/detail/<uuid:pk>/", views.BureauScoresDetailView.as_view(), name="clients_BureauScores_detail"),
    path("clients/BureauScores/update/<uuid:pk>/", views.BureauScoresUpdateView.as_view(), name="clients_BureauScores_update"),
    path("clients/BureauScores/delete/<uuid:pk>/", views.BureauScoresDeleteView.as_view(), name="clients_BureauScores_delete"),

    path("clients/Client/", views.ClientListView.as_view(), name="clients_Client_list"),
    path("clients/Client/create/", views.ClientCreateView.as_view(), name="clients_Client_create"),
    path("clients/Client/detail/<uuid:pk>/", views.ClientDetailView.as_view(), name="clients_Client_detail"),
    path("clients/Client/update/<uuid:pk>/", views.ClientUpdateView.as_view(), name="clients_Client_update"),
    path("clients/Client/delete/<uuid:pk>/", views.ClientDeleteView.as_view(), name="clients_Client_delete"),

    path("clients/PDFInformation/", views.PDFInformationListView.as_view(), name="clients_PDFInformation_list"),
    path('clients/PDFInformation/create/<uuid:client_id>/', views.PDFInformationCreateView.as_view(), name='clients_PDFInformation_create'),
    path("clients/PDFInformation/detail/<uuid:pk>/", views.PDFInformationDetailView.as_view(), name="clients_PDFInformation_detail"),
    path("clients/PDFInformation/update/<uuid:pk>/", views.PDFInformationUpdateView.as_view(), name="clients_PDFInformation_update"),
    path("clients/PDFInformation/delete/<uuid:pk>/", views.PDFInformationDeleteView.as_view(), name="clients_PDFInformation_delete"),

    path("clients/RevolvingAccountsDetails/", views.RevolvingAccountsDetailsListView.as_view(), name="clients_RevolvingAccountsDetails_list"),
    path("clients/RevolvingAccountsDetails/create/", views.RevolvingAccountsDetailsCreateView.as_view(), name="clients_RevolvingAccountsDetails_create"),
    path("clients/RevolvingAccountsDetails/detail/<uuid:pk>/", views.RevolvingAccountsDetailsDetailView.as_view(), name="clients_RevolvingAccountsDetails_detail"),
    path("clients/RevolvingAccountsDetails/update/<uuid:pk>/", views.RevolvingAccountsDetailsUpdateView.as_view(), name="clients_RevolvingAccountsDetails_update"),
    path("clients/RevolvingAccountsDetails/delete/<uuid:pk>/", views.RevolvingAccountsDetailsDeleteView.as_view(), name="clients_RevolvingAccountsDetails_delete"),

    path("clients/htmx/BureauScores/", htmx.HTMXBureauScoresListView.as_view(), name="clients_BureauScores_htmx_list"),
    path("clients/htmx/BureauScores/create/", htmx.HTMXBureauScoresCreateView.as_view(), name="clients_BureauScores_htmx_create"),
    path("clients/htmx/BureauScores/delete/<uuid:pk>/", htmx.HTMXBureauScoresDeleteView.as_view(), name="clients_BureauScores_htmx_delete"),
    path("clients/htmx/Client/", htmx.HTMXClientListView.as_view(), name="clients_Client_htmx_list"),
    path("clients/htmx/Client/create/", htmx.HTMXClientCreateView.as_view(), name="clients_Client_htmx_create"),
    path("clients/htmx/Client/delete/<uuid:pk>/", htmx.HTMXClientDeleteView.as_view(), name="clients_Client_htmx_delete"),
    path("clients/htmx/PDFInformation/", htmx.HTMXPDFInformationListView.as_view(), name="clients_PDFInformation_htmx_list"),
    path("clients/htmx/PDFInformation/create/", htmx.HTMXPDFInformationCreateView.as_view(), name="clients_PDFInformation_htmx_create"),
    path("clients/htmx/PDFInformation/delete/<uuid:pk>/", htmx.HTMXPDFInformationDeleteView.as_view(), name="clients_PDFInformation_htmx_delete"),
    path("clients/htmx/RevolvingAccountsDetails/", htmx.HTMXRevolvingAccountsDetailsListView.as_view(), name="clients_RevolvingAccountsDetails_htmx_list"),
    path("clients/htmx/RevolvingAccountsDetails/create/", htmx.HTMXRevolvingAccountsDetailsCreateView.as_view(), name="clients_RevolvingAccountsDetails_htmx_create"),
    path("clients/htmx/RevolvingAccountsDetails/delete/<uuid:pk>/", htmx.HTMXRevolvingAccountsDetailsDeleteView.as_view(), name="clients_RevolvingAccountsDetails_htmx_delete"),
)

wise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('clients/', include('clients.urls')),
    path('htmx/', views.htmx_home, name='htmx'),
    path('admin/', admin.site.urls),
]

clients/models.py
import os
import re
from django.db import models
from django.urls import reverse
import uuid

class BureauScores(models.Model):

    pdf_information = models.ForeignKey("clients.PDFInformation", on_delete=models.CASCADE)
    # Fields
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    experian_score = models.SmallIntegerField()
    equifax_score = models.SmallIntegerField()
    transunion_score = models.SmallIntegerField()
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        pass

    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse("clients_BureauScores_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("clients_BureauScores_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("clients_BureauScores_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("clients_BureauScores_htmx_delete", args=(self.pk,))


class Client(models.Model):

    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    billing_address = models.TextField(max_length=200, blank=True)
    employer_name = models.TextField(max_length=200, blank=True)
    social_security_number = models.TextField(max_length=200, blank=True)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    email = models.EmailField(blank=True)
    birthdate = models.IntegerField(null=True, blank=True)
    residential_address = models.TextField(max_length=200, blank=True)
    phone_number = models.PositiveIntegerField(null=True, blank=True)
    name = models.TextField(max_length=100, blank=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        pass

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("clients_Client_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("clients_Client_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("clients_Client_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("clients_Client_htmx_delete", args=(self.pk,))


class PDFInformation(models.Model):

    # Relationships
    client = models.ForeignKey("clients.Client", on_delete=models.CASCADE)

    # Fields
    content = models.TextField()
    file_path = models.FileField(upload_to="upload/pdfs/")
    type = models.TextField(max_length=100)
    file_name = models.TextField()
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    file_size = models.PositiveIntegerField()

    def delete(self, *args, **kwargs):
        if self.file_path:
            if os.path.isfile(self.file_path.path):
                os.remove(self.file_path.path)

        super(PDFInformation, self).delete(*args, **kwargs)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse("clients_PDFInformation_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("clients_PDFInformation_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("clients_PDFInformation_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("clients_PDFInformation_htmx_delete", args=(self.pk,))

class RevolvingAccounts(models.Model):
    pdf_data = models.ForeignKey("clients.PDFInformation", on_delete=models.CASCADE)

    account_name = models.TextField(max_length=100)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        ordering = ['account_name']

    def __str__(self):
        return f"{self.bureau} - {self.account_number}"

class RevolvingAccountsDetails(models.Model):

    # Relationships
    pdf_data = models.ForeignKey("clients.PDFInformation", on_delete=models.CASCADE)
    revolving_account = models.ForeignKey("clients.RevolvingAccounts", on_delete=models.CASCADE)

    # Fields
    bureau = models.TextField(max_length=100, null=True, blank=True)
    account_rating = models.TextField(max_length=100, null=True, blank=True)
    account = models.TextField(max_length=100, null=True, blank=True)
    past_due_amount = models.TextField(max_length=100, null=True, blank=True)
    account_type = models.TextField(max_length=100, null=True, blank=True)
    payment_frequency = models.TextField(max_length=100, null=True, blank=True)
    last_payment = models.TextField(null=True, blank=True)  # Can be null
    created = models.DateTimeField(auto_now_add=True, editable=False)
    payment_status = models.TextField(max_length=100, null=True, blank=True)
    creditor_remarks = models.TextField(max_length=100, null=True, blank=True)
    date_opened = models.TextField(null=True, blank=True)  # Can be null
    high_balance = models.TextField(max_length=100, null=True, blank=True)
    closed_date = models.TextField(null=True, blank=True)  # Can be null
    date_of_last_activity = models.TextField(null=True, blank=True)  # Can be null
    account_number = models.TextField(max_length=100, null=True, blank=True)
    credit_limit = models.TextField(max_length=100, null=True, blank=True)
    date_reported = models.TextField(null=True, blank=True)  # Can be null
    balance_owed = models.IntegerField(null=True, blank=True)
    account_status = models.TextField(max_length=100, null=True, blank=True)
    payment_amount = models.IntegerField(null=True, blank=True)
    creditor_type = models.TextField(max_length=100, null=True, blank=True)
    dispute_status = models.TextField(max_length=100, null=True, blank=True)
    last_verified = models.TextField(max_length=100, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    account_description = models.TextField(max_length=100, null=True, blank=True)
    term_length = models.TextField(max_length=100, null=True, blank=True)



    class Meta:
        pass


    def __str__(self):
        return str(self.pk)

    def clean(self):
        integer_fields = ['balance_owed', 'payment_amount', 'past_due_amount', 'high_balance', 'credit_limit']
        for field_name in integer_fields:
            value = getattr(self, field_name, None)
            if isinstance(value, str):
                cleaned_value = re.sub(r'[^\d.]', '', value)
                try:
                    setattr(self, field_name, int(float(cleaned_value)))
                except ValueError:
                    setattr(self, field_name, None)
            elif value == "--":
                setattr(self, field_name, None)


    def save(self, *args, **kwargs):
        self.clean()
        super(RevolvingAccountsDetails, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("clients_RevolvingAccountsDetails_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("clients_RevolvingAccountsDetails_update", args=(self.pk,))

    @staticmethod
    def get_htmx_create_url():
        return reverse("clients_RevolvingAccountsDetails_htmx_create")

    def get_htmx_delete_url(self):
        return reverse("clients_RevolvingAccountsDetails_htmx_delete", args=(self.pk,))

clients/forms.py
from django import forms
from . import models
import fitz



class BureauScoresForm(forms.ModelForm):
    class Meta:
        model = models.BureauScores
        fields = [
            "experian_score",
            "equifax_score",
            "transunion_score",
        ]


class ClientForm(forms.ModelForm):
    class Meta:
        model = models.Client
        fields = [
            "billing_address",
            "employer_name",
            "social_security_number",
            "email",
            "birthdate",
            "residential_address",
            "phone_number",
            "name",
        ]


class PDFInformationForm(forms.ModelForm):
    class Meta:
        model = models.PDFInformation
        fields = [
            "file_path",
            "type",
            "file_name",
            "file_size",
            "client",
        ]

    def __init__(self, *args, **kwargs):
        super(PDFInformationForm, self).__init__(*args, **kwargs)
        self.fields["client"].queryset = models.Client.objects.all()

class UploadPDFForm(forms.ModelForm):
    class Meta:
        model = models.PDFInformation
        fields = ['file_path']

    def save(self, commit=True):
        pdf_file = self.cleaned_data['file_path']
        file_name = pdf_file.name
        file_type = file_name.split('.')[-1]
        file_size = pdf_file.size

        pdf_info = models.PDFInformation(
            file_path=pdf_file,
            type=file_type,
            file_name=file_name,
            file_size=file_size,
        )
        if commit:
            pdf_info.save()
        return pdf_info

class RevolvingAccountsDetailsForm(forms.ModelForm):
    class Meta:
        model = models.RevolvingAccountsDetails
        fields = [
            "account_rating",
            "last_payment",
            "payment_status",
            "creditor_remarks",
            "date_opened",
            "high_balance",
            "closed_date",
            "date_of_last_activity",
            "account_number",
            "date_reported",
            "balance_owed",
            "account_status",
            "payment_amount",
            "creditor_type",
            "dispute_status",
            "last_verified",
            "account_description",
            "term_length",
            "pdf_data",
        ]

    def __init__(self, *args, **kwargs):
        super(RevolvingAccountsDetailsForm, self).__init__(*args, **kwargs)
        self.fields["pdf_data_id"].queryset = models.PDFInformation.objects.all()

clients/templates/clients/bureauscores_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <div>
    <input class="btn btn-danger" value="Delete BureauScores" type="submit">
  </div>
</form>
{% endblock %}

clients/templates/clients/bureauscores_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
<p>
    <a class="btn btn-light" href="{% url 'clients_BureauScores_list' %}">
    BureauScores Listing
    </a>
</p>
    
<table class="table">
    <tr><td>id</td><td>{{ object.id }}</td></tr>
    <tr><td>experian_score</td><td>{{ object.experian_score }}</td></tr>
    <tr><td>equifax_score</td><td>{{ object.equifax_score }}</td></tr>
    <tr><td>transunion_score</td><td>{{ object.transunion_score }}</td></tr>
    <tr><td>created</td><td>{{ object.created }}</td></tr>
    <tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit</a>

{% endblock %}

clients/templates/clients/bureauscores_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
<p>
    <a class="btn btn-light" href="{% url 'clients_BureauScores_list' %}">
    BureauScores Listing
    </a>
</p>
    
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.errors}}
  <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="id">id: </label>
      <input class="form-control col-sm-10"
         id="id" type="text"
         name="id" value="{{ object.id }}" disabled>
  </div>
  <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="experian_score">experian_score: </label>
      <input class="form-control col-sm-10"
         id="experian_score" type="text"
         name="experian_score" value="{{ object.experian_score }}">
  </div>
  <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="equifax_score">equifax_score: </label>
      <input class="form-control col-sm-10"
         id="equifax_score" type="text"
         name="equifax_score" value="{{ object.equifax_score }}">
  </div>
  <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="transunion_score">transunion_score: </label>
      <input class="form-control col-sm-10"
         id="transunion_score" type="text"
         name="transunion_score" value="{{ object.transunion_score }}">
  </div>
  <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="created">created: </label>
      <input class="form-control col-sm-10"
         id="created" type="datetime-local"
         name="created" value="{{ object.created }}" disabled>
  </div>
  <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="last_updated">last_updated: </label>
      <input class="form-control col-sm-10"
         id="last_updated" type="datetime-local"
         name="last_updated" value="{{ object.last_updated }}" disabled>
  </div>
  <input type="submit" value="Save" class="btn btn-primary">
</form>

{% endblock %}

clients/templates/clients/bureauscores_list.html
{% extends "base.html" %}
{% block content %}
{% for object in object_list %}
  <div class="m-2">
    <a href="{{object.get_absolute_url}}">{{object}}</a>
    <small class="ml-5">
      <a href="{% url 'clients_BureauScores_delete' object.pk %}">
        (Delete)
      </a>
    </small>
  </div>
{% endfor %}
<div>
  <a class="btn btn-primary"
    href="{% url 'clients_BureauScores_create' %}">
  Create a new BureauScores
  </a>
</div>
{% endblock %}

clients/templates/clients/client_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <div>
    <input class="btn btn-danger" value="Delete Client" type="submit">
  </div>
</form>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<p>
    <a class="btn btn-light" href="{% url 'clients_Client_list' %}">
    Client Listing
    </a>
</p>

<div class="container">
    <div class="row mb-3">
        <div class="col-sm">
            <div><strong>Created:</strong> </div>
            <div>{{ object.created }}</div>
        </div>
        <div class="col-sm">
            <div><strong>Last Updated:</strong></div>
            <div>{{ object.last_updated }}</div>
        </div>
        <div class="col-md">
            <div><strong>Social Security Number:</strong></div>
            <div>{{ object.social_security_number }}</div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md">
            <div><strong>Name:</strong></div>
            <div>{{ object.name }}</div>
        </div>
        <div class="col-md">
            <div><strong>Email:</strong> </div>
            <div>{{ object.email }}</div>
        </div>
        <div class="col-md">
            <div><strong>Phone Number:</strong></div>
            <div>{{ object.phone_number }}</div>
        </div>
        <div class="col-md">
            <div><strong>Birthdate:</strong></div>
            <div>{{ object.birthdate }}</div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md">
            <div><strong>Billing Address:</strong></div>
            <div>{{ object.billing_address }}</div>
        </div>
        <div class="col-md">
            <div><strong>Residential Address:</strong></div>
            <div>{{ object.residential_address }}</div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md">
            <div><strong>Employer Name:</strong></div>
            <div>{{ object.employer_name }}</div>
        </div>
    </div>
    <div class="mt-3">
        <a class="btn btn-sm btn-primary" href="{{object.get_update_url}}">Edit</a>
        <a class="btn btn-sm btn-danger" href="{% url 'clients_PDFInformation_create' object.id %}">Upload PDF</a>
    </div>
</div>


    
<div class="container mt-4">
    <h3>PDF Files and Credit Scores</h3>
    {% if object.pdfinformation_set.all %}
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">PDF File Name</th>
                    <th scope="col">Uploaded On</th>
                    <th scope="col" class="text-center">Experian</th>
                    <th scope="col" class="text-center">Equifax</th>
                    <th scope="col" class="text-center">TransUnion</th>
                    <th scope="col" class="text-center"></th>
                </tr>
            </thead>
            <tbody>
                {% for pdf in object.pdfinformation_set.all %}
                    {% for score in pdf.bureauscores_set.all %}
                        <tr>
                            <td>{{ pdf.file_name }}</td>
                            <td>{{ pdf.created|date:"Y-m-d H:i" }}</td>
                            <td class="text-center"><span class="badge {% if score.experian_score >= 720 %}bg-success{% elif score.experian_score >= 690 %}bg-primary{% elif score.experian_score >= 630 %}bg-info{% else %}bg-danger{% endif %} text-white">{{ score.experian_score }}</span></td>
                            <td class="text-center"><span class="badge {% if score.equifax_score >= 720 %}bg-success{% elif score.equifax_score >= 690 %}bg-primary{% elif score.equifax_score >= 630 %}bg-info{% else %}bg-danger{% endif %} text-white">{{ score.equifax_score }}</span></td>
                            <td class="text-center"><span class="badge {% if score.transunion_score >= 720 %}bg-success{% elif score.transunion_score >= 690 %}bg-primary{% elif score.transunion_score >= 630 %}bg-info{% else %}bg-danger{% endif %} text-white">{{ score.transunion_score }}</span></td>
                            <td class="text-center">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{% url 'clients_PDFInformation_detail' pdf.pk %}" class="btn btn-sm btn-secondary">View</a>
                                    <a href="{% url 'clients_PDFInformation_delete' pdf.pk %}" class="btn btn-sm btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td>{{ pdf.file_name }}</td>
                            <td>{{ pdf.created|date:"Y-m-d H:i" }}</td>
                            <td colspan="3">No scores available</td>
                            <td class="text-center">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{% url 'clients_PDFInformation_detail' pdf.pk %}" class="btn btn-sm btn-secondary">View</a>
                                    <a href="{% url 'clients_PDFInformation_delete' pdf.pk %}" class="btn btn-sm btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div>No PDF files uploaded for this client.</div>
    {% endif %}
</div>
{% endblock %}

clients/templates/clients/pdfinformation_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
<div class="container">
    <div class="row mb-3">
        <div class="col-sm">
            <div><strong>Created:</strong> </div>
            <div>{{ object.created }}</div>
        </div>
        <div class="col-sm">
            <div><strong>Last Updated:</strong></div>
            <div>{{ object.last_updated }}</div>
        </div>
        <div class="col-md">
            <div><strong>File Name:</strong></div>
            <div>{{ object.file_name }}</div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md">
            <div><strong>File Type:</strong></div>
            <div>{{ object.type }}</div>
        </div>
        <div class="col-md">
            <div><strong>File Size:</strong></div>
            <div>{{ object.file_size }}</div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md">
            <div><strong>Created:</strong></div>
            <div>{{ object.created }}</div>
        </div>
        <div class="col-md">
            <div><strong>Last Updated:</strong></div>
            <div>{{ object.last_updated }}</div>
        </div>
    </div>

    <!-- Bootstrap Accordion for RevolvingAccounts -->
    <div id="accordion">
        {% for account in object.revolvingaccounts_set.all %}
        <div class="card">
            <div class="card-header" id="heading{{ forloop.counter }}">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                        {{ account.account_name }}
                    </button>
                </h5>
            </div>

                <div class="card-body">
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th>Bureau</th>
                                <th>Account #</th>
                                <th>High Balance</th>
                                <th>Last Verified</th>
                                <th>Date of Last Activity</th>
                                <th>Date Reported</th>
                                <th>Date Opened</th>
                                <th>Balance Owed</th>
                                <th>Closed Date</th>
                                <th>Account Rating</th>
                                <th>Account Description</th>
                                <th>Dispute Status</th>
                                <th>Creditor Type</th>
                                <th>Account Status</th>
                                <th>Payment Status</th>
                                <th>Creditor Remarks</th>
                                <th>Payment Amount</th>
                                <th>Last Payment</th>
                                <th>Term Length</th>
                                <th>Past Due Amount</th>
                                <th>Account Type</th>
                                <th>Payment Frequency</th>
                                <th>Credit Limit</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for detail in account.revolvingaccountsdetails_set.all %}
                            <tr>
                                <td>{{ detail.bureau }}</td>
                                <td>{{ detail.account_number }}</td>
                                <td>{{ detail.high_balance }}</td>
                                <td>{{ detail.last_verified }}</td>
                                <td>{{ detail.date_of_last_activity }}</td>
                                <td>{{ detail.date_reported }}</td>
                                <td>{{ detail.date_opened }}</td>
                                <td>{{ detail.balance_owed }}</td>
                                <td>{{ detail.closed_date }}</td>
                                <td>{{ detail.account_rating }}</td>
                                <td>{{ detail.account_description }}</td>
                                <td>{{ detail.dispute_status }}</td>
                                <td>{{ detail.creditor_type }}</td>
                                <td>{{ detail.account_status }}</td>
                                <td>{{ detail.payment_status }}</td>
                                <td>{{ detail.creditor_remarks }}</td>
                                <td>{{ detail.payment_amount }}</td>
                                <td>{{ detail.last_payment }}</td>
                                <td>{{ detail.term_length }}</td>
                                <td>{{ detail.past_due_amount }}</td>
                                <td>{{ detail.account_type }}</td>
                                <td>{{ detail.payment_frequency }}</td>
                                <td>{{ detail.credit_limit }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}